services:
  db:
    image: mysql:9.0
    container_name: domakina-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3316:3306"
    volumes:
      - domakina_mysql_data:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - domakina_network

volumes:
  domakina_mysql_data:
    driver: local

networks:
  domakina_network:
    driver: bridge
